import { type langInfoI } from 'rw-vue-framework/controls'

const lang: langInfoI = {
  date: '日期',
  name: '姓名',
  address: '地址',
  selected: '是否选择',
  username: '用户名',
  password: '密码',
  templateSelect: '选择模板',
  treeSelect: '树选择示例',
  TITLE: '测试',
  infoid: '信息ID',
  siteid: '所属企业',
  infotitle: '文件名称',
  publishtime: '发文时间',
  issued_number: '发文字号',
  issued_name: '发文名义',
  delivery_unit: '主送单位',
  word_number: '字数',
  infotype: '文电类型',
  according_to: '依据来源',
  category: '分类',
  remark: '备注',
  addtime: '添加时间',
  updtime: '最近修改时间',
  deletetime: '删除标记',
  hz: '地区',
  year: '年份',
  num: '序号',
  season: '',
  depid: '',
  copy_for: '抄送单位',
  leading_department: '',
  contacts: '联系人',
  image: '图片',
  inputA: '姓名',
  inputB: '年龄',
  inputC: '籍贯',
  inputD: '性别',
  inputE: '工作',
  inputF: '爱好',
}
export default lang
